### ISSUE TITLE
Cannot update item

### ISSUE THREAD

**Issue by amjad** [airesvsg/acf-to-rest-api#177]
Trying to update ACF of a custom post type via the REST API `wp-json/acf/v2/custompost/5826/details`
`details` is the field I would like to edit via the REST API but I get this error:

`{
    "code": "cant_update_item",
    "message": "Cannot update item",
    "data": {
        "status": 500
    }
}`

I'm using the plugin downloaded from the WP repo.

**Comment by airesvsg** [comment]
Hi @amjad,
Please, read it: https://developer.wordpress.org/rest-api/using-the-rest-api/authentication/
Thanks

**Comment by amjad** [comment]
What about authentication? I am using the super admin login.

**Comment by airesvsg** [comment]
Hi @amjad,
Please, read it: https://developer.wordpress.org/rest-api/using-the-rest-api/authentication/
Thanks

**Comment by amjad** [comment]
I am using Application Passwords. I am able to edit everything else except the ACF meta data.

**Comment by airesvsg** [comment]
The plugin follows the pattern provided by rest api.

https://github.com/airesvsg/acf-to-rest-api/blob/master/v3/lib/endpoints/class-acf-to-rest-api-controller.php#L38

**Comment by amjad** [comment]
I don't see the v3 folder in my plugin folder.

**Comment by airesvsg** [comment]
The version 2.2.1 is the current at [WordPress Plugins Repository](https://wordpress.org/plugins/acf-to-rest-api/), since version 3 is beta.

**Comment by amjad** [comment]
So editing ACF via rest api does not work with v2?

**Comment by airesvsg** [comment]
Yes, you can edit custom post type with v2 too.

**Comment by amjad** [comment]
Can you edit acf fields of custom post types with v2? Your readme says v3.

**Comment by airesvsg** [comment]
Yes, my exemples works with v2.

Post type: To Do
http://airesgoncalves.com.br/to-do-list/

Post type: Post
http://airesgoncalves.com.br/acf-to-rest-api/

**Comment by amjad** [comment]
Yeah but I was only able to update the acf fields via this URL:

`https://localhost/demo/wp-json/wp/v2/custompost/5833/meta/149662`

Is it possible to batch update all the meta fields in one request?

**Comment by airesvsg** [comment]
Yes, it's possible to edit one or all fields in one request.

Endpoint to edit all fields:
`http://localhost/demo/wp-json/wp/v2/my-custom-post/123/`

Endpoint to edit one field:
`http://localhost/demo/wp-json/wp/v2/my-custom-post/123/my-field`

**Comment by amjad** [comment]
Thanks, what would the request and syntax for json look like? Is there an example for this?

**Comment by amjad** [comment]
I am just not able to apply CRUD operations via REST API ... see screenshot.

![screen shot 2017-09-25 at 12 35 12 pm](https://user-images.githubusercontent.com/1428634/30822375-1fb925a6-a1ee-11e7-8072-c68d03ad71c2.png)

**Comment by amjad** [comment]
Only GET is allowed for custom post type. Is there a way to change this? 

![screen shot 2017-09-25 at 12 39 52 pm](https://user-images.githubusercontent.com/1428634/30822524-aa900e56-a1ee-11e7-95f9-2e21791cc369.png)

**Comment by airesvsg** [comment]
Hi @amjad,
Please, read it: https://developer.wordpress.org/rest-api/using-the-rest-api/authentication/
Thanks

**Comment by amjad** [comment]
Thanks, this link has a bunch of things. It would be nice if you can tell me what I need to look at on this page. I would really appreciate it.

**Comment by airesvsg** [comment]
Hi @amjad,
Please, send me an email ( airesvsg@gmail.com ), I'll answer with a new version for you to test.
Thanks

**Comment by amjad** [comment]
Sent.

**Comment by martinoroma88** [comment]
I also have similar issue

**Comment by rfenaux** [comment]
Hello @airesvsg  & @amjad , how did you manage to fix this issue ?

**Comment by amjad** [comment]
@martinoroma88 @rfenaux Yes this was resolved. Sorry I was not subscribed to notifications for this issue, and just happened to come across it. You just need to send in this format: 

POST `https://YOURDOMAIN.com/wp-json/acf/v3/POST_TYPE/ID?fields[FIELD_NAME]=VALUE`

Replace the values accordingly. Cheers!

**Comment by tomhrtly** [comment]
@amjad Thanks for sharing how you managed to fix this

**Comment by u12206050** [comment]
> @martinoroma88 @rfenaux Yes this was resolved. Sorry I was not subscribed to notifications for this issue, and just happened to come across it. You just need to send in this format:
> 
> POST `https://YOURDOMAIN.com/wp-json/acf/v3/POST_TYPE/ID?fields[FIELD_NAME]=VALUE`
> 
> Replace the values accordingly. Cheers!

This only seems to work for one field at time, how can I update more than one field at a time.

When I update two fields or more I get 401 error. Even though I can update one at a time.

**Comment by AxXxel001** [comment]
Same 

> > @martinoroma88 @rfenaux Yes this was resolved. Sorry I was not subscribed to notifications for this issue, and just happened to come across it. You just need to send in this format:
> > POST `https://YOURDOMAIN.com/wp-json/acf/v3/POST_TYPE/ID?fields[FIELD_NAME]=VALUE`
> > Replace the values accordingly. Cheers!
> 
> This only seems to work for one field at time, how can I update more than one field at a time.
> 
> When I update two fields or more I get 401 error. Even though I can update one at a time.

Same problem here! When trying to update multiple fields at once via posting to

https://YOURDOMAIN.com/wp-json/acf/v3/POST_TYPE/ID

with data `{"field": "value"}`, I get the originally posted 500 error. Please help.

**Comment by americloud** [comment]
Folks, I’ll need to check my notes for this and get back.

**Comment by albertoavv** [comment]
Hello,
  If I manage to update what I cannot achieve is to create a new one, someone can help me, regards

**Comment by amjad** [comment]
https://github.com/airesvsg/acf-to-rest-api/blob/master/readme.md#editing-the-fields

**Comment by th3knigh7** [comment]
If some is still looking for how to create new post with api request , here 

send post request to this endpoint `http://nature.local/wp-json/wp/v2/POST_TYPE/?title=YOUR_TITLE&content=YOUR_CONTENT&fields[FIELD_NAME]=VALUE&fields[FIELD_NAME]=VALUE`

If you still are not able to create post with custom fields make sure you added these lines in functions.php after installing the acf-to-rest-api plugin.

`// Enable the option show in rest
add_filter( 'acf/rest_api/field_settings/show_in_rest', '__return_true' );

// Enable the option edit in rest
add_filter( 'acf/rest_api/field_settings/edit_in_rest', '__return_true' );`

and also that you have activated fields in rest api as depicted in image below. 

https://camo.githubusercontent.com/7f10b0a1f7858153fa75d282fd44feb3ae779b32/687474703a2f2f6169726573676f6e63616c7665732e636f6d2e62722f73637265656e73686f742f6163662d746f2d726573742d6170692f726561646d652f6669656c642d73657474696e67732d76332e6a7067

**Comment by lexicon2008** [comment]
so how do you also update repeater fields?

**Comment by Gautammer** [comment]
Can anyone share postman collection?

**Comment by amjad** [comment]
@Gautammer what is the issue you are facing?

**Comment by Gautammer** [comment]
i want to store user lat long in users custom acf field, but getting this shown in image please help
![Capture](https://user-images.githubusercontent.com/28038027/82110451-4cd47980-975c-11ea-8baf-9b848b34b0d2.PNG)

**Comment by Gautammer** [comment]
@amjad please check above message

**Comment by amjad** [comment]
@Gautammer do you have a development environment to test this?

**Comment by Gautammer** [comment]
@amjad no its production mode

**Comment by Gautammer** [comment]
ok this is solved and working 100% 
#141

**Comment by NikAgs** [comment]
I was still getting the 500 error after [#141](https://github.com/airesvsg/acf-to-rest-api/issues/141).

What solved it for me was adding the "if Current User is equal to Logged In" rule to my custom field": https://github.com/airesvsg/acf-to-rest-api-example/issues/1#issuecomment-183675782
