### ISSUE TITLE
Not working for options pages

### ISSUE THREAD

**Issue by ethanclevenger91** [airesvsg/acf-to-rest-api#56]
I wasn't able to post updates to options pages using the latest ACF PRO. I did some digging and come across a couple of potential problems, but I don't claim to know exactly how your plugin works.

1 - I see you're attempting to use `option` as the `post_id` argument to `acf_get_field_groups`, but this doesn't return any fields. I found that a successful call to that function for an options page looks like this:

```
array (size=18)
  'post_id' => int 0
  'post_type' => int 0
  'page_template' => int 0
  'page_parent' => int 0
  'page_type' => int 0
  'post_status' => int 0
  'post_format' => int 0
  'post_taxonomy' => null
  'taxonomy' => int 0
  'user_id' => int 0
  'user_role' => int 0
  'user_form' => int 0
  'attachment' => int 0
  'comment' => int 0
  'widget' => int 0
  'lang' => string '' (length=0)
  'ajax' => boolean false
  'options_page' => string 'site-general-settings' (length=21)
```

With the registered options page slug there at the end.

2 - It looks like the ACF Pro Options extension isn't even loaded when the API request is made. I put a `die` in the constructor for the `acf_pro_options_page` class and it never fired while making an API request. This means that when it attempts to validate the field, it doesn't find it, unless you're doing something special on your end to bootstrap that.

That's what I found, but maybe it's way off base and I totally misunderstand what's happening. Anyway, moral of the story is I can't currently update any ACF options with this plugin. Let me know if you have thoughts.

Thanks!

**Comment by specik** [comment]
Yeah, options page isn't working for me either.

**Comment by airesvsg** [comment]
Hi @ethanclevenger91 and @specik,
I'll test this.

Thanks

**Comment by airesvsg** [comment]
I tested and didn't see any problem. I recorded a video with the test, follow the link: 

[![Options Page](http://i1.ytimg.com/vi/EPZOxi2QzAI/sddefault.jpg)](https://www.youtube.com/watch?v=EPZOxi2QzAI)

https://www.youtube.com/watch?v=EPZOxi2QzAI

Thanks

**Comment by ethanclevenger91** [comment]
Your example shows a GET request, which does indeed work for me, but I'm getting the same error as @specik when trying to POST data

**Comment by airesvsg** [comment]
Hi @ethanclevenger91,
I found the error. I'll update the plugin.

Thanks

**Comment by airesvsg** [comment]
Hi @ethanclevenger91 & @specik,

I fixed the erro, but you need to add this code below in your `function.php`.

Filter reference: `{dir-acf-pro}/core/location.php:1186`

```
add_filter( 'acf/location/rule_match/options_page', function() {
    return true;
} );
```

Thanks

**Comment by bjonesy** [comment]
This is still an issue with the pro plugin.  No options show on theme option pages or sub pages.  I tried with the filter as well and it still doesn't work.

**Comment by ethanclevenger91** [comment]
@airesvsg The above code causes all fields to show when I'm using ACF fields outside of the admin, like the following scenario: https://www.advancedcustomfields.com/resources/create-a-front-end-form/
